spring:
  application:
    name: health_tracker

  Jackson:
    time-zone: ${user.timezone}

  datasource:
    url: jdbc:postgresql://localhost:5433/health_tracker
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

admin:
  username: admin
  password: 1234


jwt:
  secret: rYr156a2F01sX4A7Cv+6/mQa0zZbO8GhEbIuJ+Nrbk0=
  expiration: 900000

frontend: { url: http://localhost:3000 }
  
logging:
  level:
    org:
      springframework:
        web: ERROR
      hibernate:
        sql: ERROR

